version: "3.8"

services: 
  nestjs:
    build:
      context: .
      target: prod
    # command: npm run start:debug
    env_file: .env
    volumes:
      - .:/node/app
      - /node/app/node_modules
    ports:
      - ${PORT_API}:${PORT_API}
      - 9229:9229
    networks:
      - back-end

  mongo:
    image: mongo:4.2-bionic
    container_name: mongo
    restart: unless-stopped
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - mongo-db:/data/db
    ports:
      - "27017-27019:27017-27019"
    networks:
      - back-end
      - db

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}      
    networks:
      - db

networks:
  back-end:
  db:

volumes:
  mongo-db:

